classDiagram

  subgraph Component_1
    class CatalogCategoryRelations {
      +String sys_id (required, unique)
      +String sys_updated_by (required, default: "admin")
      +Date sys_created_on (required)
      +Number sys_mod_count (required, default: 0)
      +String external_id (default: "")
      +String source (required)
      +Date sys_updated_on (required)
      +String sys_tags (default: "")
      +String sys_created_by (required, default: "admin")
      +String external_source (default: "")
      +String target (required)
      +ObjectId catalog (required)
      +ObjectId category (required)
      +ObjectId _id
      +Number __v
    }
    class ProductOfferingCatalog {
      +String name (required)
      +String code (required, unique)
      +Date start_date (required)
      +Date end_date (default: null)
      +String status (required, enum: [published,draft,archived,retired], default: "draft")
      +String hierarchy_json (default: "")
      +String description
      +String external_id (default: "")
      +Boolean is_default (default: false)
      +String number (required, unique)
      +String sys_id (required, unique)
      +String sys_updated_by (required)
      +Date sys_created_on (required)
      +String sys_created_by (required)
      +Date sys_updated_on (required)
      +Number sys_mod_count (default: 0)
      +String sys_tags (default: "")
      +String external_source (default: "")
      +ObjectId _id
      +Date createdAt
      +Date updatedAt
      +Number __v
    }
    class ProductOfferingCategory {
      +String name (required)
      +String code (required, unique)
      +Boolean is_leaf (required, default: false)
      +Date start_date (required)
      +Date end_date (default: null)
      +String status (required, enum: [published,draft,archived,retired], default: "draft")
      +String description
      +String image
      +String thumbnail
      +String number (required, unique)
      +String sys_id (required, unique)
      +String sys_created_by (required)
      +String sys_updated_by (required)
      +Date sys_created_on (required)
      +Date sys_updated_on (required)
      +Number sys_mod_count (default: 0)
      +String external_id
      +String sys_tags
      +String leaf_categories
      +String external_source
      +ObjectId _id
      +Date createdAt
      +Date updatedAt
    }
    class ProductOffering {
      +Array category
      +Array channel
      +String description
      +String externalId (default: "")
      +String id
      +String sys_id
      +String internalId
      +String lastUpdate (default: "")
      +String name (required)
      +Array productOfferingPrice
      +String productOfferingTerm (default: "")
      +ObjectId productSpecification
      +Array prodSpecCharValueUse
      +Embedded validFor
      +String version
      +String status
      +String lifecycleStatus
      +String href
      +ObjectId _id
      +Number __v
    }
    class ProductSpecification {
      +String sys_id (required, unique)
      +String display_name
      +String specification_category
      +String specification_type
      +String start_date
      +String description
      +String status
      +ObjectId _id
      +Date createdAt
      +Date updatedAt
      +Number __v
    }
  end

  subgraph Component_2
    class Opportunity {
      +String sys_id (required, unique)
      +String short_description
      +String assignment_group
      +Date estimated_closed_date
      +Date actual_closed_date
      +String description
      +Number term_month
      +String industry
      +String source
      +String sales_cycle_type
      +Number score
      +String contact
      +Number probability
      +Boolean do_not_share
      +String stage
      +Boolean do_not_email
      +Boolean do_not_call
      +String account
      +String price_list
      +String number
      +ObjectId _id
      +Date createdAt
      +Date updatedAt
      +Number __v
    }
  end

  subgraph Component_3
    class OpportunityLine {
      +String cumulative_acv
      +String service_location
      +Embedded product_offering
      +String term_month
      +String external_id
      +String sys_updated_on
      +String number
      +String sys_id (required, unique)
      +Embedded price_list
      +Embedded unit_of_measurement
      +String cumulative_tcv
      +String sys_updated_by
      +String sys_created_on
      +String unit_net_price
      +String cumulative_arr
      +String sys_created_by
      +String quantity
      +String sys_mod_count
      +String cumulative_mrr
      +Embedded opportunity
      +String sys_tags
      +String unit_list_price
      +String total_one_time_price
      +String work_notes
      +String external_system
      +ObjectId _id
      +Number __v
    }
  end

  subgraph Component_4
    class PriceList {
      +String sys_id (required, unique)
      +String name
      +String description
      +String state
      +String defaultflag
      +String currency
      +Date validFor.startDateTime
      +Date validFor.endDateTime
      +ObjectId _id
      +Date createdAt
      +Date updatedAt
      +Number __v
    }
  end

  subgraph Component_5
    class ProductOfferingPrice {
      +String sys_id (required, unique)
      +String id
      +String name
      +Embedded price
      +String lifecycleStatus
      +Embedded validFor
      +Embedded productOffering
      +String priceType
      +String recurringChargePeriodType
      +Embedded unitOfMeasure
      +Embedded priceList
      +String @type
      +String state
      +String href
      +ObjectId _id
      +Number __v
    }
  end

  subgraph Component_6
    class quotes {
      +String number (required, unique)
      +String sys_id (required, unique)
      +String channel (required)
      +String state
      +String version (required)
      +String total_amount
      +String currency
      +String assigned_to
      +String assignment_group
      +String subscription_start_date
      +String subscription_end_date
      +String short_description
      +String account
      +String active (default: "true")
      +ObjectId _id
      +Number __v
    }
  end

  subgraph Component_7
    class User {
      +String serviceNowId (required)
      +String firstName (required)
      +String lastName (required)
      +String email (required, unique)
      +String mobilePhone (required)
      +String password (required)
      +String type (required, enum: [individual,company])
      +String companyName
      +Number location.latitude
      +Number location.longitude
      +String location.address
      +String location.city
      +String location.state
      +String location.country
      +String location.postalCode
      +Date createdAt (default: undefined)
      +Date updatedAt (default: undefined)
      +ObjectId _id
      +Number __v
    }
  end

  CatalogCategoryRelations --> ProductOfferingCatalog : "catalog"
  CatalogCategoryRelations --> ProductOfferingCategory : "category"
  ProductOffering --> ProductOfferingCategory : "category"
  ProductOffering --> ProductSpecification : "productSpecification"
